# Generated by Django 4.0 on 2021-12-19 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_department_remove_companyposition_department_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_head',
        ),
    ]
