# Generated by Django 4.0 on 2021-12-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_remove_department_is_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyposition',
            name='office_number',
        ),
        migrations.AddField(
            model_name='employee',
            name='office_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
