# Generated by Django 4.0 on 2022-04-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previous_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='previous login'),
        ),
    ]
