# Generated by Django 4.0 on 2022-03-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Zensko'), ('M', 'Musko')], max_length=1, null=True),
        ),
    ]
