# Generated by Django 4.0 on 2022-03-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Ženski'), ('M', 'Muški')], max_length=1, null=True),
        ),
    ]
