# Generated by Django 4.0 on 2022-04-04 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_previous_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='previous_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 4, 12, 55, 45, 230744), null=True, verbose_name='previous login'),
        ),
    ]
