# Generated by Django 4.0 on 2022-04-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_previous_login'),
        ('users', '0003_alter_user_gender'),
    ]

    operations = [
    ]
