# Generated by Django 4.0 on 2022-02-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_location',
            field=models.CharField(choices=[('BL', 'Banja Luka'), ('BG', 'Beograd')], default='BL', max_length=2),
        ),
    ]
