# Generated by Django 4.0 on 2022-04-04 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_previous_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='previous_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 4, 23, 15, 52, 165583), null=True, verbose_name='previous login'),
        ),
    ]
