# Generated by Django 4.0 on 2022-04-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_previous_login'),
        ('users', '0004_merge_0002_user_previous_login_0003_alter_user_gender'),
    ]

    operations = [
    ]
