# Generated by Django 4.0 on 2022-04-13 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20220405_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='previous_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 13, 9, 3, 52, 26593), null=True, verbose_name='previous login'),
        ),
    ]
