# Generated by Django 4.0 on 2022-04-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('edited_date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=48)),
                ('details', models.CharField(blank=True, max_length=256, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('repeat_days', models.IntegerField(blank=True, default=0, null=True)),
                ('repeat_every_year', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('Rođendan', 'Rođendan'), ('Sastanak', 'Sastanak'), ('Daily', 'Daily'), ('Planiranje', 'Planiranje')], max_length=20, null=True)),
            ],
        ),
    ]
