# Generated by Django 4.0 on 2022-03-27 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_alter_event_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Birthday', 'Rođendan'), ('Meeting', 'Sastanak'), ('Daily', 'Daily'), ('Planning', 'Planiranje')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='shared',
            field=models.ManyToManyField(related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
