# Generated by Django 4.0 on 2022-03-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_type_alter_event_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, choices=[('Rođendan', 'Rođendan'), ('Sastanak', 'Sastanak'), ('Daily', 'Daily'), ('Planiranje', 'Planiranje')], max_length=20, null=True),
        ),
    ]
