# Generated by Django 4.0 on 2022-04-04 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_alter_user_previous_login'),
        ('news', '0003_alter_comment_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes_comment',
            field=models.ManyToManyField(related_name='likes_dislikes_comment', through='news.LikeDislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likedislike',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.comment'),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle'),
        ),
    ]
