# Generated by Django 4.0 on 2021-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('surname', models.CharField(max_length=35)),
                ('title', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
