# Generated by Django 4.0 on 2021-12-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=200)),
                ('employeeDateOfJoining', models.DateField()),
                ('employeeDepartment', models.CharField(max_length=500)),
                ('employeeGender', models.BooleanField(default=False)),
            ],
        ),
    ]
