# Generated by Django 4.0 on 2021-12-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrbicPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeDateOfJoining',
            field=models.CharField(max_length=200),
        ),
    ]
