# Generated by Django 4.0 on 2021-12-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='position',
            name='sector_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.sector'),
        ),
    ]
